### ISSUE TITLE
Webpage doesn't show anything

### ISSUE THREAD

**Issue by px100** [tushki1405/Airline-Reservation#1]
localhost port :: 3000

the webpage doesn't show or load the service tabs (Airline, Airline schedule or Reservation). ??

**Comment by tushki1405** [comment]
Have you tried setting up the project? You have to run/deploy the code and the database for the application to run. Please see the README.
Let me know if you still can't get it to work.

**Comment by px100** [comment]
The project is up. 
Database code is deployed/run.
Still doesn't run.

btw, I'm trying it to run on Visual Studio Pro 2015 + MS SQL Server 2014
