### ISSUE TITLE
Issues in step 2

### ISSUE THREAD

**Issue by Shoaib3210** [tushki1405/Airline-Reservation#2]
Sir, I am unable to open web browser in the 2nd step. I have run the solution and found the update connection in web config, but i cant update. Please help me with this. If u can please provide a video tutorial for the same. Please reply ASAP.
My email id- mohdshoaib1318@gmail.com

**Comment by tushki1405** [comment]
Hi, I just saw this comment. Were you able to run the project? Are you getting any error?
